package cn.hexing.ami.service.main.insMgt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2016-06-06T15:28:33.374+08:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://ifs.service.ami.hexing.cn/", name = "InstallationFBServiceInf")
public interface InstallationFBServiceInf {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "installFeedBack", targetNamespace = "http://ifs.service.ami.hexing.cn/", className = "com.test.InstallFeedBack")
    @WebMethod
    @ResponseWrapper(localName = "installFeedBackResponse", targetNamespace = "http://ifs.service.ami.hexing.cn/", className = "com.test.InstallFeedBackResponse")
    public java.lang.String installFeedBack(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
